version: "3.9"
services:
  db:
    image: postgres
    tty: true
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - "db_data:/var/lib/postgresql/data/pgdata"
      - "db_log:/var/logs"
volumes:
  db_data: {}
  db_log: {}
