version: "3.7"

services:
  db:
    container_name: postgre_db
    image: postgres:14
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password

volumes:
  db: {}
