/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package read

import io.ktor.server.engine.*
import io.ktor.server.netty.*
import read.plugins.*

fun main() {
    embeddedServer(Netty, port = 8080, host = "0.0.0.0") {
        configureRouting()
    }.start(wait = true)
}